-
  text_html:
    - "The fish were laboring<br/>"
    - "There was no car in sight<br/>"
    - "Go to the place<br/>"
    - "Where there is no sunlight"
  video_url: "https://www.youtube.com/embed/pOhce-7MJYI"
  location: "apartment"
  destination: "garage"
