default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: vandalay_industries_development

test:
  <<: *default
  database: vandalay_industries_test

production:
  <<: *default
  database: vandalay_industries
